name: Build images

on:
  schedule:
    - cron: '0 14 * * *' # Midnight AEST
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64,arm

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build multipaper-master
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: noevidenz/multipaper-master
          target: master
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Build multipaper
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: noevidenz/multipaper
          target: server
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

#      - name: Build
#        run: |
#          docker build --platform linux/amd64,linux/arm64,linux/arm/v7 --push --target master -t noevidenz/multipaper-master .
#          docker build --platform linux/amd64,linux/arm64,linux/arm/v7 --push --target server -t noevidenz/multipaper .

      - name: Clean up cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache