name: Build from Releases

on:
  schedule:
    - cron: '0 14 * * *' # Midnight AEST
  workflow_dispatch:

jobs:
  build_1-20:
    name: Build Release 1.20
    uses: ./.github/workflows/build-release.yaml
    with:
      version: "1.20"
      master_tags: chscompclub/multipaper-master:1.20
      server_tags: chscompclub/multipaper:1.20
    secrets: inherit
  buid_isteigertest:
    name: Build isteiger_test
    uses: ./.github/workflows/build-isteigertest.yaml
    with:
      version: "1.20"
      master_tags: chscompclub/multipaper-master:isteiger_test
      server_tags: chscompclub/multipaper:isteiger_test
      master_url: https://api.multipaper.io/v2/projects/multipaper/versions/1.20.1/builds/26/downloads/multipaper-master-2.11.0-all.jar
    secrets: inherit
    

  build_1-19:
    name: Build Release 1.19
    uses: ./.github/workflows/build-release.yaml
    with:
      version: "1.19"
      master_tags: chscompclub/multipaper-master:1.19
      server_tags: chscompclub/multipaper:1.19
    secrets: inherit

  build_1-18:
    name: Build release 1.18
    uses: ./.github/workflows/build-release.yaml
    with:
      version: "1.18"
      master_tags: chscompclub/multipaper-master:1.18
      server_tags: chscompclub/multipaper:1.18
    secrets: inherit
